/**
 * content/internalMechanismActions.ARCHIVE.ts —— 🔒 只读素材存档，**禁止被任何客户端代码 import**
 *
 * ⚠️ 为什么单独成一个文件、而不是留在 internalMechanisms.ts 里：
 *
 * 2026-09-15 实测发现：把 actions 作为 INTERNAL_MECHANISMS 对象的一个属性，
 * 即使没有任何渲染路径读它，它依然会被打进客户端 bundle
 * （`dist/_astro/match.astro_*.js`）—— 因为它是模块级 const 对象上的一个
 * **活属性**，打包器无法静态证明「永远不会被读」，于是整表保留。
 * 后果：用户在 DevTools 里能读到我们刻意删掉的「解决方法」原文，
 * 以及 sudden_loss 这类内部代号。
 *
 * 拆成独立文件后，只要**没有任何 import 引用它**，它就不进入产物。
 * 由 engine_suite.mjs 第 16 节 + mech_render_probe.mjs 双重守护这条不变量。
 *
 * 产品决策（用户明确指示）：不提供解决方法。
 * 本文件仅作素材存档，不是为了启用。
 */

export const INTERNAL_MECHANISM_ACTIONS_ARCHIVE: Record<string, string[]> = {
  choice_friction: [      '**The Somatic Coin Toss:** Assign each choice to heads and tails. Flip the coin. Pay attention only to the split-second feeling in your gut while the coin is in the air—not the result. *Mechanism: Bypasses the prefrontal cortex\'s analysis paralysis and directly taps into your somatic intuition regarding loss aversion.*',
      '**The Erasure Rule:** Write your two options on a piece of paper. You are forced to cross one out immediately. Notice the physical resistance in your hand. *Mechanism: Materializes the mental "tearing" into a physical action, forcing you to confront the reality of relinquishing an option.*',
      '**Information Detox:** Mute or unfollow one external source of advice or comparison for three days. *Mechanism: Reclaims decision-making sovereignty and cuts off the subconscious escape route of outsourcing responsibility.*',
  ],
  scarcity_panic: [      '**The Abundance Anchor:** Place the highest denomination bill you have in your wallet and do not spend it for 7 days. *Mechanism: Provides a physical baseline of resources every time you open your wallet, soothing the evolutionary hoarding instinct triggered by Ice Age stress.*',
      '**The Somatic Descent:** When panic hits, place one hand on your belly and breathe into it for 3 deep breaths. *Mechanism: Forcibly pulls the anxiety generated by an "imagined future" back into the safety of the present physical body.*',
      '**The Intentional Nourishment:** Prepare one simple meal for yourself and eat it without looking at any screens. *Mechanism: Sends a safety signal to your deep subconscious that you have adequate resources and the capability to care for yourself.*',
  ],
  boundary_invasion: [      '**The Shielding Shower:** When showering, let the water run down your shoulders and explicitly visualize it washing away the expectations and energy of everyone else you carried today. *Mechanism: Rebuilds a missing "self-outline" through somatic visualization.*',
      '**The DND Barrier:** Put your phone on \'Do Not Disturb\' for exactly one hour every evening. *Mechanism: Overcomes the evolutionary fear of "tribal ostracism." You are physically enforcing the boundary that you are inaccessible, proving to your nervous system that setting limits will not result in abandonment.*',
      '**The Doorway Reclaim:** Clean or replace your front doormat. *Mechanism: Redefines on a subconscious level exactly who and what is permitted to enter your personal territory.*',
  ],
  stagnation_void: [      '**The Morning Light Reset:** For the next three days, before looking at your phone, open a window and let direct sunlight hit your face for 2 minutes. *Mechanism: Resets melatonin and circadian rhythms, physically breaking the "psychological hibernation" state at a genetic level.*',
      '**The Micro-Chaos Protocol:** Wear a color or a piece of jewelry you haven\'t worn in months. *Mechanism: Sends a weak but undeniable signal of change to the brain, disrupting the paralysis caused by perfectionism.*',
      '**The Vacuum Principle:** Completely empty one small drawer or shelf today. Leave it empty. *Mechanism: Creates a physical vacuum in your environment, subconsciously signaling that your life now has the capacity to hold new energy.*',
  ],
  identity_crisis: [      '**The Avatar Update:** Change your phone and computer wallpapers to an image that represents who you are becoming, not who you were. *Mechanism: Provides a visual anchor to combat the self-doubt and procrastination that occurs during the transition between old and new identities.*',
      '**The Wardrobe Purge:** Donate or throw away one piece of clothing that clearly belongs to the "old you" or a past role you played. *Mechanism: Ends the physical occupation of your old identity, stopping the subconscious emission of "submissive signals" to your environment.*',
      '**The Route Variation:** Walk or drive a different route to a familiar destination. *Mechanism: Uses a change in physical movement to force the nervous system to experience that you do not have to operate according to the old script.*',
  ],
  toxic_loop: [      '**The Spatial Disruption:** Move a significant piece of furniture (like your bed or desk) to a different angle today. *Mechanism: Breaks the "familiarity heuristic" by forcing your brain to recalculate space in a known environment, thereby interrupting old habit loops.*',
      '**The Temperature Shock:** When you feel the urge to engage in the toxic pattern, run cold water over your wrists for 10 seconds. *Mechanism: Triggers the mammalian dive reflex to forcibly activate the vagus nerve, instantly snapping the impulse of compulsive repetition.*',
      '**Scent Unlinking:** Change your daily perfume, room spray, or body wash immediately. *Mechanism: The olfactory bulb is directly connected to the limbic system (memory and emotion). Changing scents is the fastest way to sever the neural link to a toxic attachment.*',
  ],
  sudden_loss: [],
  illusion_fixation: [      '**The Reality Tap:** Splash cold water on your eyes and face. *Mechanism: Interrupts the brain\'s high-speed "pattern recognition" and over-imagination, using intense physical sensation to drag your consciousness back into the 3D world.*',
      '**The Containment Protocol:** Set a timer for 10 minutes. Allow yourself to obsess, romanticize, and overthink completely. When the timer rings, you must stop and do a physical chore. *Mechanism: Instead of forcibly suppressing the illusion (which causes it to rebound), this creates a strict physical and temporal container for the obsession.*',
      '**The Digital Anchor:** Change the notification sound for the specific person or app you are fixated on to a boring, generic tone. *Mechanism: Weakens the conditioned reflex of the dopamine reward circuit, eliminating unnecessary suggestions of "destiny."*',
  ],
};
